server:
  port: 8080
spring:
  application:
    name: spring-ai-lmstudio
  ai:
    openai:
      base-url: http://127.0.0.1:1234
      api-key: lmstudio
      chat:
        options:
          model: ${LMSTUDIO_MODEL}
    mcp:
      client:
        toolcallback:
          enabled: true
        streamable-http:
          connections:
            tavily-server:
              url: "https://mcp.tavily.com"
              endpoint: "/mcp?tavilyApiKey=${TAVILY_API_KEY}"
tools:
  toload:
    - tavily_search
    - tavili_extract